[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd client && npm ci --include=dev && npm run build",
  "cd server && npm ci --omit=dev"
]

[phases.build]
cmds = []

[start]
cmd = "cd server && npm start"
